# Generated by Django 5.2.5 on 2025-09-01 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('published_date', models.DateField()),
            ],
        ),
    ]
